### ISSUE TITLE
Certificate issue on your website

### ISSUE THREAD

**Issue by differentieel** [pepijndevos/pepijndevos.github.com#2]
hi Pepijn, your website has a Certificate issue - maybe a renew will help - compliments for your creative work and website, ferrie

**Comment by pepijndevos** [comment]
From what I can tell this has always worked and is supposed to "just work" on github pages? https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https

I can't find anything in their docs where you can or should set up a custom certificate, or gives me the option to renew the certificate.
